spring:
  jpa:
    database: POSTGRESQL
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
  sql:
    init:
      platform: postgresql
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/academia_db
    username: postgres
    password: admin123456

api:
  security:
    token:
      secret: ${JWT_SECRET:my-secrety-key}
 
server:
  port: 8090